### PR TITLE
Documented AccountSettings

### PR DESCRIPTION
**Pull request by CSEndeavour**
Add documentation to classes related to AccountSettings. Fixed bug with Register page going to android home screen instead of the login page. Changed main activity in the manifest to LoginView.

### CODE REVIEW

**Review by julianmarrero — APPROVED** [review]
Nice job adding the Javadoc makes it much clearer to go through. Looks good to me

**Review by JerryLi-617 — APPROVED** [review]
Good documentation, code is easy to follow and understand

**Comment by ChowdhuryShaswata** [comment]
Fix conflict in manifest file - keep one of each class.

**Review by ChowdhuryShaswata — APPROVED** [review]
Good documentation - this should be fine to pull.

**Pull request merged**
